name: Python CI + Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
	#Step 1: Get your code
      - name: Checkout code
        uses: actions/checkout@v4

	#Step 2: Setup Python to run tests
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

	#Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

	#Step 4: Run tests (optional - remove if you don't have tests yet)
      - name: Run tests
        run: |
	  if [ -f test_main.py ]; then pytest -q; else echo "No tests found"; fi

	#Step 5: Build the Docker image
      - name: Build Docker image
	run: docker build -t flaskapp:latest .
